server:
  port: 9090

# Config Server client, Mysql
spring:
  cloud:
    config:
      uri:
      - http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/db_products
    username: root
    password: root

# Eureka client
eureka:
 instance:
   hostname: localhost
 client:
   register-with-eureka: true
   fetch-registry: true  
   serviceUrl:
     defaultZone: http://${eureka.instance.hostname}:8761/eureka/

# Oauth2 JWT JWK Key Set Token
security:
  oauth2:
   resource:
      jwk:
        key-set-uri: http://localhost:8204/.well-known/jwks.json

# logging
logging:
  level:
    root: INFO
    sun:
     rmi: ERROR
    org:
     springframework:
      security:
       web:
        FilterChainProxy: DEBUG

# Errors code
errors:
  messageBusinessErrorException: 
    code: 001
    message: Error in the business logic
  messageArgumentNotValidException:
    code: 002
    message: Parameters not valid
  messageNotFoundException:
    code: 003
    message: Record not found
  messageParameterMandatoryException:
    code: 004
    message: Parameters mandatory not found
  
# Oauth2 Roles
oauth2:
  roles:
    saveMovementType: ADMIN

# Swagger Open API info
swagger:
   applicationDescription: Microservicio de Gestion de Productos para sistemas Ecommerce
   applicationVersion: v1.0.0
   applicationTitle: Microservicio de Gestion de Productos
   termsOfService: http://swagger.io/terms
   license: Apache 2.0
   licenseUrl: http://springdoc.org
   contactName: Yadickson Vasquez
   contactEmail: yadicksonvasquez@gmail.com
