server:
  port: 9090

# Config Server client, Mysql
spring:
  cloud:
    config:
      uri:
      - http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/db_products
    username: root
    password: root

# Eureka client
eureka:
 instance:
   hostname: localhost
 client:
   register-with-eureka: true
   fetch-registry: true  
   serviceUrl:
     defaultZone: http://${eureka.instance.hostname}:8761/eureka/

# Oauth2 JWT JWK Key Set Token
security:
  oauth2:
   resource:
      jwk:
        key-set-uri: http://localhost:8204/.well-known/jwks.json

# logging
logging:
  level:
    root: INFO
    sun:
     rmi: ERROR
    org:
     springframework:
      security:
       web:
        FilterChainProxy: DEBUG

# Errors code
errors:
  movementTypeSaveException: 
    code: 001
    message: Inventory Movement Type not saved
  methodArgumentNotValidException:
    code: 002
    message: Parameters not valid
  
# Oauth2 Roles
oauth2:
  roles:
    saveMovementType: ADMIN